### PR TITLE
Create server express

### LINKED ISSUE #1: Create a node server
Create a server using node.js and express

### PR DESCRIPTION
**Pull request by dantehemerson**
Closes #1 
Create the server with express and add a basic structure.
I hope you accept my PR to continue continuing with the project.

I wanted to ask you:
what database will be used ?, I recommend mongodb.

### CODE REVIEW

**Comment by shreevari** [comment]
I think the plan was to use PostgreSQL, but we can discuss about the options. Why do you feel MongoDB will be a good fit?

**Comment by sanjithpk** [comment]
We will use PostgresSQL, because we already have a schema, I'll host that on Heroku as well.

**Comment by dantehemerson** [comment]
@shreevari @sanjithpk 
Ok, let's use postgress.
I plan to use Sequelize as ORM what do you think?

**Comment by sanjithpk** [comment]
@dantehemerson  Hmm, are you familiar with knex.js? Check out the docs, it pretty simple to use. Let's use that as it has more functionality than an ORM. Also we need to use CORS and also for storing passwords I prefer bcrypt, if you have anything better for hashing passwords, you can share.

PS, can you tell me more about why ORM is needed, I'm not familiar with Sequelize.

**Comment by shreevari** [comment]
@suresh-44 What is your opinion about using Sequelize here?

**Comment by shreevari** [comment]
@dantehemerson @sanjithpk @suresh-44 
It would be appropriate to move this discussion to #5

**Pull request merged**
